### ISSUE TITLE
Highlight 'Disabled fixers (manually)' in darker red

### ISSUE THREAD

**Issue by weshooper** [mlocati/php-cs-fixer-configurator#30]
If our config array contains `'class_keyword_remove' => false,` to ensure it's disabled, then it'd be useful if the rule were listed with a red background. Currently it's listed with a white background.

A darker shade of red than the excluded from presets colour might make sense, it'd be nicely consistent with the two shades of green used.

**Comment by mlocati** [comment]
It's listed with a white background if you import `'class_keyword_remove' => false` when there's no rule set that contains the `'class_keyword_remove'` rule.
So, it's like if the `'class_keyword_remove' => false` line wasn't there, since it doesn't have any effect.
I'm not going to change that behavior.

**Comment by weshooper** [comment]
@mlocati understood, thanks for looking into!
